# Generated by Django 4.1.1 on 2022-10-16 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_book_contributor_review_bookcontributor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='first_name',
            new_name='first_names',
        ),
        migrations.RenameField(
            model_name='contributor',
            old_name='last_name',
            new_name='last_names',
        ),
    ]
